### ISSUE TITLE
Collections missing a yaml file example

### ISSUE THREAD

**Issue by brentporter** [In-For-Disaster-Analytics/metadata-schema#1]
Just as we have yamls for the other digital objects, we should have one for collections

**Comment by paul-csr** [comment]
Working on this during the week of 27 Nov.

**Comment by brentporter** [comment]
Any updates on this (also added Greg to this one)

**Comment by paul-csr** [comment]
Brent,

I uploaded the new Collection YAML this morning
https://github.com/In-For-Disaster-Analytics/metadata-schema/tree/main/examples_and_templates

Also re-named the other YAMLs to remove the TDIS prefix.

-Paul
________________________________

**Comment by gsmithhart** [comment]
Thanks Paul.
